
DROP TABLE ADDRESS;
DROP TABLE SERVICES;
DROP TABLE EMPLOYEES;
DROP TABLE CLIENTS;
DROP SEQUENCE CLIENTS_SEC;
DROP SEQUENCE ADDRESS_SEC;
DROP SEQUENCE EMPLOYEES_SEC;
DROP SEQUENCE SERVICES_SEC;
DROP TABLE ADDRESS;
DROP TABLE SERVICES;
DROP TABLE EMPLOYEES;
DROP TABLE CLIENTS;
DROP SEQUENCE CLIENTS_SEC;
DROP SEQUENCE ADDRESS_SEC;
DROP SEQUENCE EMPLOYEES_SEC;
DROP SEQUENCE SERVICES_SEC;


create table SERVICES(
	SERVICEID number NOT NULL,
	SERVICENAME varchar2(4000) NOT NULL,
	STARTDATE date NOT NULL,
	COST number NOT NULL
	
	
);

alter table SERVICES add(
	constraint SERVICE_PK primary key (SERVICEID)
);

create sequence SERVICES_SEC start with 1;

create or replace trigger SERVICE_auto_increment
before insert on SERVICES
for each row

begin
	select SERVICES_SEC.nextval
	into :new.SERVICEID
	from dual;
end;
/


INSERT INTO SERVICES (SERVICENAME,STARTDATE,COST) VALUES ('Tarmacking',TO_DATE('01/01/2022','DD/MM/YY'),2000);
INSERT INTO SERVICES (SERVICENAME,STARTDATE,COST) VALUES ('Bricklaying',TO_DATE('02/02/2022','DD/MM/YY'),1500);
INSERT INTO SERVICES (SERVICENAME,STARTDATE,COST) VALUES ('Waste Disposal',TO_DATE('03/03/2022','DD/MM/YY'),500);
INSERT INTO SERVICES (SERVICENAME,STARTDATE,COST) VALUES ('Roofing Services',TO_DATE('04/04/2022','DD/MM/YY'),1250);


create table EMPLOYEES(
	EMPLOYEEID number NOT NULL, 
	FORENAME varchar2(4000) NOT NULL,
	SURNAME varchar2(4000) NOT NULL,
	STARTDATE date NOT NULL,
	TELEPHONE char(11) NOT NULL,
	SERVICEID number NOT NULL,
	constraint serviceid_fk foreign key (SERVICEID) REFERENCES SERVICES(SERVICEID),
	constraint employee_forename_length CHECK (lengthb(FORENAME)<20),
	constraint employee_surname_length CHECK (lengthb(SURNAME)<20)

);


alter table EMPLOYEES add(
	constraint EMPLOYEES_PK primary key (EMPLOYEEID)
);

create sequence EMPLOYEES_SEC start with 1;

create or replace trigger EMPLOYEES_auto_increment
before insert on EMPLOYEES
for each row

begin
	select EMPLOYEES_SEC.nextval
	into :new.EMPLOYEEID
	from dual;
end;
/


INSERT INTO EMPLOYEES (FORENAME,SURNAME,STARTDATE,TELEPHONE,SERVICEID) VALUES ('Naeem','Barr',TO_DATE('19/02/1968', 'DD/MM/YY'),'07618944654','1');
INSERT INTO EMPLOYEES (FORENAME,SURNAME,STARTDATE,TELEPHONE,SERVICEID) VALUES ('Gabriel','Powell',TO_DATE('28/04/1969', 'DD/MM/YY'),'07702966779','2');
INSERT INTO EMPLOYEES (FORENAME,SURNAME,STARTDATE,TELEPHONE,SERVICEID) VALUES ('Rebeca','Mcleod',TO_DATE('02/05/1969', 'DD/MM/YY'),'07378466161','4');
INSERT INTO EMPLOYEES (FORENAME,SURNAME,STARTDATE,TELEPHONE,SERVICEID) VALUES ('Fleur','Patton',TO_DATE('06/10/1971', 'DD/MM/YY'),'07153806095','1');
INSERT INTO EMPLOYEES (FORENAME,SURNAME,STARTDATE,TELEPHONE,SERVICEID) VALUES ('Owen','Walter',TO_DATE('05/11/1971', 'DD/MM/YY'),'07803294870','2');
INSERT INTO EMPLOYEES (FORENAME,SURNAME,STARTDATE,TELEPHONE,SERVICEID) VALUES ('Veronika','Lister',TO_DATE('12/01/1973', 'DD/MM/YY'),'07825207408','1');
INSERT INTO EMPLOYEES (FORENAME,SURNAME,STARTDATE,TELEPHONE,SERVICEID) VALUES ('Emre','Bryan',TO_DATE('05/02/1974', 'DD/MM/YY'),'07623866547','2');
INSERT INTO EMPLOYEES (FORENAME,SURNAME,STARTDATE,TELEPHONE,SERVICEID) VALUES ('Fern','Barr',TO_DATE('06/01/1975', 'DD/MM/YY'),'07925260165','4');
INSERT INTO EMPLOYEES (FORENAME,SURNAME,STARTDATE,TELEPHONE,SERVICEID) VALUES ('Naeem','Carrillo',TO_DATE('31/10/1975', 'DD/MM/YY'),'07903813119','3');
INSERT INTO EMPLOYEES (FORENAME,SURNAME,STARTDATE,TELEPHONE,SERVICEID) VALUES ('Blossom','Sweet',TO_DATE('19/12/1975', 'DD/MM/YY'),'07185046285','4');
INSERT INTO EMPLOYEES (FORENAME,SURNAME,STARTDATE,TELEPHONE,SERVICEID) VALUES ('Danyl','Sanford',TO_DATE('23/09/1976', 'DD/MM/YY'),'07978439276','3');
INSERT INTO EMPLOYEES (FORENAME,SURNAME,STARTDATE,TELEPHONE,SERVICEID) VALUES ('Mahdi','Coates',TO_DATE('11/02/1977', 'DD/MM/YY'),'07923371190','1');
INSERT INTO EMPLOYEES (FORENAME,SURNAME,STARTDATE,TELEPHONE,SERVICEID) VALUES ('Arron','Irvine',TO_DATE('21/12/1977', 'DD/MM/YY'),'07513213276','3');
INSERT INTO EMPLOYEES (FORENAME,SURNAME,STARTDATE,TELEPHONE,SERVICEID) VALUES ('Alba','Kramer',TO_DATE('13/07/1978', 'DD/MM/YY'),'07173427828','4');
INSERT INTO EMPLOYEES (FORENAME,SURNAME,STARTDATE,TELEPHONE,SERVICEID) VALUES ('Haseeb','Olson',TO_DATE('09/03/1979', 'DD/MM/YY'),'07158507905','2');


create table CLIENTS(
	CLIENTID number NOT NULL, 
	FORENAME varchar2(4000) NOT NULL,
	SURNAME varchar2(4000) NOT NULL,
	DOB date NOT NULL,
	TELEPHONE char(11) NOT NULL,
	SERVICEID number NOT NULL,
	XCOORD number NOT NULL,
	YCOORD number NOT NULL,
	constraint clientserviceid_fk foreign key (SERVICEID) REFERENCES SERVICES(SERVICEID),
	constraint forename_length CHECK (lengthb(FORENAME)<20),
	constraint surname_length CHECK (lengthb(SURNAME)<20)

);

alter table CLIENTS add(
	constraint CLIENTS_PK primary key (CLIENTID),
	constraint xcheck CHECK (XCOORD BETWEEN -10 and 10),
	constraint ycheck CHECK (YCOORD BETWEEN -10 and 10),
	constraint client_forename_length CHECK (lengthb(FORENAME)<20),
	constraint client_surname_length CHECK (lengthb(SURNAME)<20) 

	
);

create sequence CLIENTS_SEC start with 1;

create or replace trigger CLIENTS_auto_increment
before insert on CLIENTS
for each row

begin
	select CLIENTS_SEC.nextval
	into :new.CLIENTID
	from dual;
end;
/

INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Casey','Benton',TO_DATE('16/03/1965', 'DD/MM/YY'),'07863153356','1',5,-1);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Grayson','Booker',TO_DATE('12/07/1965', 'DD/MM/YY'),'07647438276','3',-3,10);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Haley','Woodward',TO_DATE('01/10/1965', 'DD/MM/YY'),'07746880491','2',-9,9);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Skyla','Mendoza',TO_DATE('01/02/1966', 'DD/MM/YY'),'07187208883','1',6,-3);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Jaylon','Zimmerman',TO_DATE('29/07/1966', 'DD/MM/YY'),'07920704013','2',-10,1);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Haiden','Velez',TO_DATE('08/02/1967', 'DD/MM/YY'),'07443631296','2',-6,7);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Ciara','Esparza',TO_DATE('07/04/1967', 'DD/MM/YY'),'07528740809','1',3,-7);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Barbara','Gilmore',TO_DATE('23/05/1967', 'DD/MM/YY'),'07955416369','4',8,8);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Junior','Bonilla',TO_DATE('15/04/1968', 'DD/MM/YY'),'07628607715','1',-1,0);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Asher','Nelson',TO_DATE('19/06/1969', 'DD/MM/YY'),'07285622898','3',10,6);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Krish','Quinn',TO_DATE('10/05/1973', 'DD/MM/YY'),'07539231661','2',9,-4);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Angelina','Stuart',TO_DATE('16/05/1974', 'DD/MM/YY'),'07979057035','1',7,-9);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Enrique','Bryan',TO_DATE('08/08/1974', 'DD/MM/YY'),'07321489543','3',-5,-4);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Aileen','Welch',TO_DATE('12/04/1976', 'DD/MM/YY'),'07524355786','2',-9,10);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Antonio','Atkinson',TO_DATE('13/04/1976', 'DD/MM/YY'),'07900767320','1',6,-5);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Leslie','Lowery',TO_DATE('01/07/1976', 'DD/MM/YY'),'07789476075','1',-2,-1);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Declan','Cooke',TO_DATE('26/08/1977', 'DD/MM/YY'),'07775438916','4',5,-9);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Naima','Robbins',TO_DATE('20/10/1977', 'DD/MM/YY'),'07758072986','1',-4,-4);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Sasha','Dean',TO_DATE('11/07/1978', 'DD/MM/YY'),'07281179983','4',-7,-6);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Zara','Holmes',TO_DATE('10/10/1978', 'DD/MM/YY'),'07181848498','3',-7,-6);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Emilie','Donovan',TO_DATE('16/04/1979', 'DD/MM/YY'),'07558581339','2',9,-9);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Randy','Kelley',TO_DATE('16/05/1979', 'DD/MM/YY'),'07755256846','3',-8,-10);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Marisa','Fitzpatrick',TO_DATE('27/11/1979', 'DD/MM/YY'),'07521548638','1',1,-5);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Jude','Avery',TO_DATE('31/12/1979', 'DD/MM/YY'),'07444897211','3',-2,6);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Cash','Mccullough',TO_DATE('19/03/1980', 'DD/MM/YY'),'07834184700','2',1,3);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Jorge','Higgins',TO_DATE('26/10/1965', 'DD/MM/YY'),'07842671225','4',7,-8);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Kamora','Collins',TO_DATE('28/12/1965', 'DD/MM/YY'),'07527510203','1',-1,-3);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Donald','Fagen',TO_DATE('21/02/1966', 'DD/MM/YY'),'07252622488','4',5,10);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Walter','Becker',TO_DATE('30/01/1967', 'DD/MM/YY'),'07975543721','2',-6,-4);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Jerry','Garcia',TO_DATE('11/08/1971', 'DD/MM/YY'),'07747694696','2',-4,-1);
INSERT INTO CLIENTS (FORENAME,SURNAME,DOB,TELEPHONE,SERVICEID,XCOORD,YCOORD) VALUES ('Jon','Riley',TO_DATE('21/11/1966', 'DD/MM/YY'),'07459066270','3',-3,4);


create table ADDRESS(
	XYID number NOT NULL,
	XCOORD number NOT NULL,
	YCOORD number NOT NULL,
	CLIENTID number NOT NULL,
	constraint clientid_fk foreign key (CLIENTID) REFERENCES CLIENTS(CLIENTID)

	
);

alter table ADDRESS add(
	constraint XY_PK primary key (XYID)
);

create sequence ADDRESS_SEC start with 1;

create or replace trigger ADDRESS_auto_increment
before insert on ADDRESS
for each row

begin
	select ADDRESS_SEC.nextval
	into :new.XYID
	from dual;
end;
/

INSERT INTO ADDRESS(XCOORD,YCOORD,CLIENTID)
SELECT XCOORD,YCOORD,CLIENTID FROM CLIENTS;

